import groovy.json.JsonSlurper

plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'maven-publish'
    id 'de.undercouch.download' version '5.6.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

architectury {
    minecraft = minecraft_version
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    group = rootProject.maven_group
    version = rootProject.mod_version

    repositories {
        mavenCentral()
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

task setupLibrary {
    doLast {
        def base = "https://www.minecrafttransitrailway.com/libs/\${mtr_version}/"
        download {
            src "\${base}MTR-common-\${minecraft_version}-\${mtr_version}-dev.jar"
            dest file("checkouts/mtr-common.jar")
            overwrite true
        }
        download {
            src "\${base}MTR-fabric-\${minecraft_version}-\${mtr_version}-dev-shadow.jar"
            dest file("checkouts/mtr-fabric.jar")
            overwrite true
        }
        download {
            src "\${base}MTR-forge-\${minecraft_version}-\${mtr_version}-dev-shadow.jar"
            dest file("checkouts/mtr-forge.jar")
            overwrite true
        }
    }
}

subprojects {
    tasks.matching { it.name in ['compileJava', 'classes', 'build'] }.configureEach {
        dependsOn rootProject.tasks.named('setupLibrary')
    }
}
