plugins {
    id 'dev.architectury.loom'
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    silentMojangMappingsLicense()
}

dependencies {
    forge "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    modImplementation "dev.architectury:architectury-forge:${architectury_version}"
    modImplementation "maven.modrinth:mtr:${mtr_version}"
    implementation project(':common')
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand version: project.version }
}
